// zombie_04.rvmat - 11:25:41 07/02/12, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	 //  = 0,	// Error parsing: Empty enum name
};

ambient[] = {0.54, 0.58, 0.52, 3.5};
diffuse[] = {0.5, 0.55, 0.5, 1.0};
forcedDiffuse[] = {0.12, 0.3, 0.32, 0.7};
emmisive[] = {0.5, 0.8, 0.7, 0.12};
specular[] = {0.026, 0.025, 0.025, 0.3};
specularPower = 120.0;
PixelShaderID = "Skin";
VertexShaderID = "Skin";

class Stage1 {
	class uvTransform {
		aside[] = {1.0, 0.0, 0.0};
		up[] = {0.0, 1.0, 0.0};
		dir[] = {0.0, 0.0, 0.0};
		pos[] = {0.0, 0.0, 0.0};
	};
	texture = "dayz\textures\faces\zombie_04_nohq.paa";
	uvSource = "tex";
};

class Stage2 {
	texture = "dayz\textures\faces\zombie_04_co.paa";
	uvSource = "tex";
};

class Stage3 {
	texture = "ca\characters\heads\male\defaulthead\data\hhl_white_sdm.paa";
	uvSource = "tex";
};

class Stage4 {
	texture = "ca\characters\heads\male\defaulthead\data\hhl_as.paa";
	uvSource = "tex";
};

class Stage5 {
	texture = "dayz\textures\faces\zombie_04_smdi.paa";
	uvSource = "tex";
};

class Stage6 {
	texture = "#(ai,64,1,1)fresnel(1.422,1.973)";
	uvSource = "none";
};
